blog/config/routes.rb
Rails.application.routes.draw do
  get 'welcome/index'
  resources :articles do
    resources :comments
  end
  root 'welcome#index'
end

blog/app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

blog/app/models/article.rb
class Article < ApplicationRecord
    has_many :comments, dependent: :destroy
  validates :title, presence: true,
                    length: { minimum: 5 }

end

blog/app/models/comment.rb
class Comment < ApplicationRecord
  belongs_to :article
end

blog/app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
end

blog/app/controllers/articles_controller.rb
class ArticlesController < ApplicationController
    def index
        @articles = Article.all
      end

    def show
        @article = Article.find(params[:id])
      end
    
    def new
        @article = Article.new
    end

    def edit
        @article = Article.find(params[:id])
      end

    def create
        @article = Article.new(article_params)
 
        if @article.save
            redirect_to @article
          else
            render 'new'
        end
    end

    def update
        @article = Article.find(params[:id])
       
        if @article.update(article_params)
          redirect_to @article
        else
          render 'edit'
        end
      end

      def destroy
        @article = Article.find(params[:id])
        @article.destroy
       
        redirect_to articles_path
      end
       
      private
        def article_params
          params.require(:article).permit(:title, :text)
        end
end

blog/app/controllers/comments_controller.rb
class CommentsController < ApplicationController
    def create
      @article = Article.find(params[:article_id])
      @comment = @article.comments.create(comment_params)
      redirect_to article_path(@article)
    end

    def destroy
        @article = Article.find(params[:article_id])
        @comment = @article.comments.find(params[:id])
        @comment.destroy
        redirect_to article_path(@article)
      end
   
    private
      def comment_params
        params.require(:comment).permit(:commenter, :body)
      end
  end

blog/app/controllers/welcome_controller.rb
class WelcomeController < ApplicationController
  def index
  end
end

blog/app/helpers/application_helper.rb
module ApplicationHelper
end

blog/app/helpers/articles_helper.rb
module ArticlesHelper
end

blog/app/helpers/welcome_helper.rb
module WelcomeHelper
end

blog/app/views/articles/edit.html.erb
<h1>Edit article</h1>

<%= form_with(model: @article, local: true) do |form| %>
 
  <% if @article.errors.any? %>
    <div id="error_explanation">
      <h2>
        <%= pluralize(@article.errors.count, "error") %> prohibited
        this article from being saved:
      </h2>
      <ul>
        <% @article.errors.full_messages.each do |msg| %>
          <li><%= msg %></li>
        <% end %>
      </ul>
    </div>
  <% end %>
 
  <p>
    <%= form.label :title %><br>
    <%= form.text_field :title %>
  </p>
 
  <p>
    <%= form.label :text %><br>
    <%= form.text_area :text %>
  </p>
 
  <p>
    <%= form.submit %>
  </p>
 
<% end %>


 
<%= link_to 'Back', articles_path %>

blog/app/views/articles/form.html.erb
<%= form_with model: @article, local: true do |form| %>
 
    <% if @article.errors.any? %>
      <div id="error_explanation">
        <h2>
          <%= pluralize(@article.errors.count, "error") %> prohibited
          this article from being saved:
        </h2>
        <ul>
          <% @article.errors.full_messages.each do |msg| %>
            <li><%= msg %></li>
          <% end %>
        </ul>
      </div>
    <% end %>
   
    <p>
      <%= form.label :title %><br>
      <%= form.text_field :title %>
    </p>
   
    <p>
      <%= form.label :text %><br>
      <%= form.text_area :text %>
    </p>
   
    <p>
      <%= form.submit %>
    </p>
   
  <% end %>
  

blog/app/views/articles/index.html.erb
<h1>Listing articles</h1>
<%= link_to 'New article', new_article_path %>
<table>
  <tr>
    <th>Title</th>
    <th>Text</th>

    <th colspan="3"></th>
  </tr>
 
  <% @articles.each do |article| %>
    <tr>
      <td><%= article.title %></td>
      <td><%= article.text %></td>
      <td><%= link_to 'Show', article_path(article) %></td>
      <td><%= link_to 'Edit', edit_article_path(article) %></td>
      <td><%= link_to 'Destroy', article_path(article),
              method: :delete,
              data: { confirm: 'Are you sure?' } %></td>

    </tr>
  <% end %>
</table>

blog/app/views/articles/new.html.erb
<h1>New article</h1>
<%= form_with scope: :article, url: articles_path, local: true do |form| %>

    <% if @article.errors.any? %>
    <div id="error_explanation">
      <h2>
        <%= pluralize(@article.errors.count, "error") %> prohibited
        this article from being saved:
      </h2>
      <ul>
        <% @article.errors.full_messages.each do |msg| %>
          <li><%= msg %></li>
        <% end %>
      </ul>
    </div>
  <% end %>

    <p>
      <%= form.label :title %><br>
      <%= form.text_field :title %>
    </p>
   
    <p>
      <%= form.label :text %><br>
      <%= form.text_area :text %>
    </p>
   
    <p>
      <%= form.submit %>
    </p>
  <% end %>
  
  <%= render 'form' %>

  <%= link_to 'Back', articles_path %>

blog/app/views/articles/show.html.erb
<p>
  <strong>Title:</strong>
  <%= @article.title %>
</p>
 
<p>
  <strong>Text:</strong>
  <%= @article.text %>
</p>

<h2>Comments</h2>
<%= render @article.comments %>

<h2>Add a comment:</h2>
<%= render 'comments/form' %>

<%= link_to 'Edit', edit_article_path(@article) %> |

<%= link_to 'Back', articles_path %>

blog/app/views/comments/_comment.html.erb
<p>
  <strong>Commenter:</strong>
  <%= comment.commenter %>
</p>
 
<p>
  <strong>Comment:</strong>
  <%= comment.body %>
</p>

<p>
  <%= link_to 'Destroy Comment', [comment.article, comment],
               method: :delete,
               data: { confirm: 'Are you sure?' } %>
</p>

blog/app/views/comments/_form.html.erb
<%= form_with(model: [ @article, @article.comments.build ], local: true) do |form| %>
    <p>
      <%= form.label :commenter %><br>
      <%= form.text_field :commenter %>
    </p>
    <p>
      <%= form.label :body %><br>
      <%= form.text_area :body %>
    </p>
    <p>
      <%= form.submit %>
    </p>
  <% end %>

blog/app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>Blog</title>
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>

    <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_include_tag 'application', 'data-turbolinks-track': 'reload' %>
  </head>

  <body>
    <%= yield %>
  </body>
</html>

blog/app/views/welcome/index.html.erb
<h1>Hello, Rails!</h1>
<%= link_to 'My Blog', controller: 'articles' %>